In [13]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# Create scaler object and data

In [14]:
scaler = MinMaxScaler(feature_range=(0, 1))
data = np.array([[-10, 20], [-0.5, 16], [0, 1], [125, 18]])
data

array([[-10. ,  20. ],
       [ -0.5,  16. ],
       [  0. ,   1. ],
       [125. ,  18. ]])

# Fit scaler to data and transform

In [15]:
scaler = scaler.fit(data)
data_scaled = scaler.transform(data)
data_scaled

array([[0.        , 1.        ],
       [0.07037037, 0.78947368],
       [0.07407407, 0.        ],
       [1.        , 0.89473684]])

# Inverse the transformation

In [18]:
orig_data = scaler.inverse_transform(data_scaled)
orig_data

array([[-10. ,  20. ],
       [ -0.5,  16. ],
       [  0. ,   1. ],
       [125. ,  18. ]])